(()=>{"use strict";
const K="library_management_ultimate_v6",S="library_management_session_v6",T="library_management_theme_v6";
const EMPTY={settings:{allowedDomains:[],loanDays:14,maxLoans:5,maxRenewals:2,dailyFine:5,reservationLimit:3,libraryName:"Library Management"},users:[],books:[],loans:[],reservations:[],fines:[],notifications:[],audit:[]};
let db=read();let page="dashboard";let search="";
const $=s=>document.querySelector(s), esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function read(){try{return {...structuredClone(EMPTY),...JSON.parse(localStorage.getItem(K)||"{}")}}catch{return structuredClone(EMPTY)}}
function save(){localStorage.setItem(K,JSON.stringify(db))}
function session(){try{return JSON.parse(sessionStorage.getItem(S)||"null")}catch{return null}}
function setSession(u){sessionStorage.setItem(S,JSON.stringify({id:u.id,role:u.role}))}
function logout(){sessionStorage.removeItem(S);login()}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+"_"+Math.random()}
function nameOK(v){return /^[A-Za-z ]+$/.test(v)&&v.trim().length>0}
function userOK(v){return /^[A-Za-z_]+$/.test(v)&&v.length>=3&&v.length<=30}
function emailParts(v){return v.match(/^([A-Za-z0-9._%+-]+)@([A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+){1,2})$/)}
function emailOK(v,domains){const m=emailParts(v);return !!m&&domains.includes(m[2].toLowerCase())}
function phoneOK(v){return /^\d{7,15}$/.test(v)}
function isbnOK(v){let x=v.replace(/[- ]/g,"");return /^(\d{9}[\dXx]|\d{13})$/.test(x)}
function currentUser(){const s=session();return s?db.users.find(u=>u.id===s.id):null}
function theme(){return localStorage.getItem(T)||"system"}
function applyTheme(){let t=theme();document.documentElement.dataset.theme=t==="system"?(matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light"):t}
applyTheme();
function login(){document.body.innerHTML=`<main class="auth"><section class="card auth-card"><div class="auth-logo">Library Management</div><p class="muted">Sign in</p><form id="login"><label>Username</label><input name="username" required autocomplete="username"><label>Password</label><input name="password" type="password" required autocomplete="current-password"><div id="fb" class="feedback"></div><div class="mt"><button class="btn" style="width:100%">Sign in</button></div></form></section></main>`;$("#login").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),u=db.users.find(x=>x.username===f.get("username")),fb=$("#fb");if(!u){fb.innerHTML='<span class="error">No such user.</span>';return}if(u.password!==f.get("password")){fb.innerHTML='<span class="error">Wrong password.</span>';return}setSession(u);render()}}
function setup(){document.body.innerHTML=`<main class="auth"><section class="card auth-card"><div class="auth-logo">Library Management</div><p class="muted">Administrator setup</p><form id="setup"><label>Name</label><input name="name" required><label>Username</label><input name="username" required><label>Email</label><input name="email" required><label>Password</label><input name="password" type="password" required><div id="fb" class="feedback"></div><div class="mt"><button class="btn" style="width:100%">Create Administrator</button></div></form></section></main>`;$("#setup").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),n=f.get("name").trim(),un=f.get("username"),em=f.get("email").toLowerCase(),pw=f.get("password"),fb=$("#fb"),m=emailParts(em);if(!nameOK(n))return fb.textContent="Name may contain only alphabets and spaces.";if(!userOK(un))return fb.textContent="Username may contain only alphabets and underscores.";if(db.users.some(x=>x.username===un))return fb.textContent="Username already exists.";if(!m)return fb.textContent="Enter a valid email address.";let domain=m[2].toLowerCase();db.settings.allowedDomains=[domain];if(pw.length<8)return fb.textContent="Password must contain at least 8 characters.";db.users.push({id:uid(),name:n,username:un,email:em,password:pw,role:"admin",createdAt:Date.now()});save();setSession(db.users.at(-1));render()}}
const adminNav=[["dashboard","Dashboard"],["books","Books"],["members","Members"],["circulation","Circulation"],["reservations","Reservations"],["fines","Fines"],["reports","Reports"],["notifications","Notifications"],["audit","Audit Log"],["settings","Settings"]];
function nav(){return `<nav class="side">${adminNav.map(x=>`<button class="${page===x[0]?"active":""}" data-page="${x[0]}">${x[1]}</button>`).join("")}</nav><nav class="mobile-nav">${adminNav.map(x=>`<button class="${page===x[0]?"active":""}" data-page="${x[0]}">${x[1]}</button>`).join("")}</nav>`}
function shell(body){let u=currentUser();document.body.innerHTML=`<div class="app"><header class="top"><div class="brand">Library Management</div><div class="top-right"><span class="user-chip">${esc(u.name)} · ${u.role==="admin"?"Admin":"Member"}</span><button class="btn secondary sm" id="themeBtn">Theme</button><button class="btn secondary sm" id="logout">Sign out</button></div></header><div class="layout">${u.role==="admin"?nav():""}<main class="main">${body}</main></div></div>`;$("#logout").onclick=logout;$("#themeBtn").onclick=cycleTheme;document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{page=b.dataset.page;render()})}
function cycleTheme(){let x=theme(),n=x==="system"?"light":x==="light"?"dark":"system";localStorage.setItem(T,n);applyTheme();render()}
function dashboard(){let overdue=db.loans.filter(l=>!l.returned&&l.dueDate<new Date().toISOString().slice(0,10)).length;return `<h1>Dashboard</h1><div class="grid g4"><div class="card kpi"><div class="label">Books</div><div class="value">${db.books.length}</div></div><div class="card kpi"><div class="label">Members</div><div class="value">${db.users.filter(u=>u.role==="member").length}</div></div><div class="card kpi"><div class="label">Issued</div><div class="value">${db.loans.filter(l=>!l.returned).length}</div></div><div class="card kpi"><div class="label">Overdue</div><div class="value">${overdue}</div></div></div><div class="grid g2 mt"><section class="card pad"><h3>Inventory</h3>${inventorySummary()}</section><section class="card pad"><h3>Quick actions</h3><div class="actions"><button class="btn" data-action="book">Add Book</button><button class="btn secondary" data-action="member">Add Member</button><button class="btn secondary" data-action="issue">Issue Book</button></div></section></div>`}
function inventorySummary(){let total=db.books.reduce((a,b)=>a+b.copies,0),avail=db.books.reduce((a,b)=>a+b.available,0),p=total?Math.round(avail/total*100):0;return `<div class="statline"><span>Total copies</span><b>${total}</b></div><div class="statline"><span>Available</span><b>${avail}</b></div><div class="statline"><span>Utilization</span><b>${100-p}%</b></div><div class="progress mt"><i style="width:${100-p}%"></i></div>`}
function books(){let q=search.toLowerCase(),a=db.books.filter(b=>[b.title,b.author,b.isbn,b.publisher,b.genre,b.tags].join(" ").toLowerCase().includes(q));return `<div class="toolbar"><div><h1>Books</h1><span class="muted small">${a.length} result(s)</span></div><div class="actions"><input id="search" value="${esc(search)}" placeholder="Search books"><button class="btn" data-action="book">Add Book</button></div></div><section class="card pad">${a.length?`<div class="table-wrap"><table class="table"><tr><th>Title</th><th>Author</th><th>ISBN</th><th>Genre</th><th>Copies</th><th>Available</th><th>Price</th><th></th></tr>${a.map(b=>`<tr><td><b>${esc(b.title)}</b></td><td>${esc(b.author)}</td><td>${esc(b.isbn)}</td><td>${esc(b.genre)}</td><td>${b.copies}</td><td>${b.available}</td><td>₹${Number(b.price||0).toFixed(2)}</td><td><button class="btn danger sm" data-delete-book="${b.id}">Delete</button></td></tr>`).join("")}</table></div>`:`<div class="empty">No books.</div>`}</section>`}
function members(){let a=db.users.filter(u=>u.role==="member");return `<div class="toolbar"><div><h1>Members</h1><span class="muted small">${a.length} member(s)</span></div><button class="btn" data-action="member">Add Member</button></div><section class="card pad">${a.length?`<div class="table-wrap"><table class="table"><tr><th>Name</th><th>Username</th><th>Email</th><th>Phone</th><th>Type</th><th></th></tr>${a.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.username)}</td><td>${esc(u.email)}</td><td>${esc(u.phone)}</td><td>${esc(u.memberType)}</td><td><button class="btn danger sm" data-delete-user="${u.id}">Delete</button></td></tr>`).join("")}</table></div>`:`<div class="empty">No members.</div>`}</section>`}
function circulation(){let a=db.loans;return `<div class="toolbar"><div><h1>Circulation</h1><span class="muted small">${a.length} record(s)</span></div><button class="btn" data-action="issue">Issue Book</button></div><section class="card pad">${a.length?`<div class="table-wrap"><table class="table"><tr><th>Book</th><th>Member</th><th>Issue</th><th>Due</th><th>Status</th><th></th></tr>${a.map(l=>{let b=db.books.find(x=>x.id===l.bookId),u=db.users.find(x=>x.id===l.memberId),od=!l.returned&&l.dueDate<new Date().toISOString().slice(0,10);return `<tr><td>${esc(b?.title)}</td><td>${esc(u?.name)}</td><td>${l.issueDate}</td><td>${l.dueDate}</td><td><span class="badge ${od?"bad":""}">${l.returned?"Returned":od?"Overdue":"Issued"}</span></td><td>${l.returned?"":`<button class="btn success sm" data-return="${l.id}">Return</button>`}</td></tr>`}).join("")}</table></div>`:`<div class="empty">No circulation records.</div>`}</section>`}
function reservations(){return `<div class="toolbar"><h1>Reservations</h1></div><section class="card pad">${db.reservations.length?`<div class="table-wrap"><table class="table"><tr><th>Book</th><th>Member</th><th>Placed</th><th>Status</th></tr>${db.reservations.map(r=>`<tr><td>${esc(db.books.find(b=>b.id===r.bookId)?.title)}</td><td>${esc(db.users.find(u=>u.id===r.memberId)?.name)}</td><td>${r.date}</td><td>${esc(r.status)}</td></tr>`).join("")}</table></div>`:`<div class="empty">No reservations.</div>`}</section>`}
function fines(){return `<div class="toolbar"><h1>Fines</h1></div><section class="card pad">${db.fines.length?`<div class="table-wrap"><table class="table"><tr><th>Member</th><th>Book</th><th>Amount</th><th>Status</th><th></th></tr>${db.fines.map(f=>`<tr><td>${esc(db.users.find(u=>u.id===f.memberId)?.name)}</td><td>${esc(db.books.find(b=>b.id===f.bookId)?.title)}</td><td>₹${Number(f.amount).toFixed(2)}</td><td>${f.paid?"Paid":"Outstanding"}</td><td>${f.paid?"":`<button class="btn success sm" data-pay="${f.id}">Mark paid</button>`}</td></tr>`).join("")}</table></div>`:`<div class="empty">No fines.</div>`}</section>`}
function reports(){let total=db.books.reduce((s,b)=>s+b.copies,0),value=db.books.reduce((s,b)=>s+b.copies*Number(b.price||0),0),out=db.fines.filter(f=>!f.paid).reduce((s,f)=>s+Number(f.amount),0);return `<h1>Reports</h1><div class="grid g3"><div class="card pad"><h3>Inventory value</h3><div class="kpi"><div class="value">₹${value.toFixed(2)}</div></div></div><div class="card pad"><h3>Total copies</h3><div class="kpi"><div class="value">${total}</div></div></div><div class="card pad"><h3>Outstanding fines</h3><div class="kpi"><div class="value">₹${out.toFixed(2)}</div></div></div></div><section class="card pad mt"><h3>Genre distribution</h3>${genreReport()}</section><div class="actions mt"><button class="btn secondary" data-export="books">Export Books CSV</button><button class="btn secondary" data-export="members">Export Members CSV</button><button class="btn secondary" data-export="loans">Export Loans CSV</button><button class="btn secondary" data-export="backup">Backup JSON</button></div>`}
function genreReport(){let m={};db.books.forEach(b=>m[b.genre]=(m[b.genre]||0)+b.copies);let e=Object.entries(m);return e.length?e.map(([k,v])=>`<div class="statline"><span>${esc(k)}</span><b>${v}</b></div>`).join(""):`<div class="empty">No data.</div>`}
function notifications(){return `<h1>Notifications</h1><section class="card pad">${db.notifications.length?db.notifications.slice().reverse().map(n=>`<div class="notice mt"><b>${esc(n.title)}</b><div class="muted small">${esc(n.text)}</div></div>`).join(""):`<div class="empty">No notifications.</div>`}</section>`}
function audit(){return `<h1>Audit Log</h1><section class="card pad">${db.audit.length?`<div class="table-wrap"><table class="table"><tr><th>Time</th><th>User</th><th>Action</th><th>Details</th></tr>${db.audit.slice().reverse().map(a=>`<tr><td>${new Date(a.time).toLocaleString()}</td><td>${esc(a.user)}</td><td>${esc(a.action)}</td><td>${esc(a.details)}</td></tr>`).join("")}</table></div>`:`<div class="empty">No audit records.</div>`}</section>`}
function settings(){let s=db.settings;return `<h1>Settings</h1><div class="grid g2"><section class="card pad"><h3>Library rules</h3><form id="settings"><label>Library name</label><input name="libraryName" value="${esc(s.libraryName)}" required><label>Allowed email domains</label><input name="domains" value="${esc((s.allowedDomains||[]).join(", "))}" placeholder="name.ac.in"><label>Loan period (days)</label><input name="loanDays" type="number" min="1" max="365" value="${s.loanDays}"><label>Maximum active loans</label><input name="maxLoans" type="number" min="1" max="100" value="${s.maxLoans}"><label>Maximum renewals</label><input name="maxRenewals" type="number" min="0" max="20" value="${s.maxRenewals}"><label>Daily fine</label><input name="dailyFine" type="number" min="0" max="100000" step=".01" value="${s.dailyFine}"><label>Reservation limit</label><input name="reservationLimit" type="number" min="0" max="100" value="${s.reservationLimit}"><div class="actions mt"><button class="btn">Save settings</button></div></form></section><section class="card pad"><h3>Appearance</h3><p class="muted">Choose the interface theme.</p><div class="actions"><button class="btn secondary" data-theme="light">Light</button><button class="btn secondary" data-theme="dark">Dark</button><button class="btn secondary" data-theme="system">System</button></div><h3 class="mt">Data</h3><div class="actions"><button class="btn secondary" data-export="backup">Backup JSON</button><label class="btn secondary" style="display:inline-block">Restore JSON<input id="restore" type="file" accept=".json" hidden></label><button class="btn danger" id="clearData">Clear all data</button></div></section></div>`}
function member(){let u=currentUser(),loans=db.loans.filter(l=>l.memberId===u.id&&!l.returned),res=db.reservations.filter(r=>r.memberId===u.id&&r.status!=="cancelled"),fine=db.fines.filter(f=>f.memberId===u.id&&!f.paid),book=id=>db.books.find(b=>b.id===id);return `<h1>My Profile</h1><div class="grid g2"><section class="card pad"><div class="profile-head"><div class="avatar">${esc(u.name[0].toUpperCase())}</div><div><h2>${esc(u.name)}</h2><span class="muted">${esc(u.memberType||"Member")}</span></div></div><div class="statline"><span>Username</span><b>${esc(u.username)}</b></div><div class="statline"><span>Email</span><b>${esc(u.email)}</b></div><div class="statline"><span>Phone</span><b>${esc(u.phone||"")}</b></div></section><section class="card pad"><h3>Outstanding fines</h3>${fine.length?fine.map(f=>`<div class="statline"><span>${esc(book(f.bookId)?.title)}</span><b>₹${Number(f.amount).toFixed(2)}</b></div>`).join(""):`<div class="empty">No outstanding fines.</div>`}</section><section class="card pad"><h3>Currently issued</h3>${loans.length?`<div class="table-wrap"><table class="table"><tr><th>Book</th><th>Due</th><th>Status</th></tr>${loans.map(l=>`<tr><td>${esc(book(l.bookId)?.title)}</td><td>${l.dueDate}</td><td>${l.dueDate<new Date().toISOString().slice(0,10)?'<span class="bad">Overdue</span>':'Issued'}</td></tr>`).join("")}</table></div>`:`<div class="empty">No issued books.</div>`}</section><section class="card pad"><h3>Reserved books</h3>${res.length?res.map(r=>`<div class="statline"><span>${esc(book(r.bookId)?.title)}</span><span class="badge">${esc(r.status)}</span></div>`).join(""):`<div class="empty">No reservations.</div>`}</section></div>`}
function modal(type){let body="",title="";if(type==="book"){title="Add Book";body=`<form id="modalForm"><div class="two"><div><label>Title</label><input name="title" maxlength="200" required></div><div><label>Author</label><input name="author" maxlength="120" required></div><div><label>ISBN</label><input name="isbn" required></div><div><label>Publisher</label><input name="publisher" maxlength="120"></div><div><label>Publication year</label><input name="year" type="number" min="1000" max="${new Date().getFullYear()+1}"></div><div><label>Genre</label><input name="genre" maxlength="60" required></div><div><label>Tags</label><input name="tags" maxlength="300"></div><div><label>Copies</label><input name="copies" type="number" min="1" max="10000" value="1" required></div><div><label>Price</label><input name="price" type="number" min="0" max="100000000" step=".01" value="0"></div><div><label>Rating</label><input name="rating" type="number" min="0" max="5" step=".1" value="0"></div></div><label>Cover URL</label><input name="cover" type="url" placeholder="https://"><div id="mfb" class="feedback"></div><div class="actions mt"><button class="btn">Add Book</button></div></form>`}
if(type==="member"){title="Add Member";body=`<form id="modalForm"><div class="two"><div><label>Name</label><input name="name" required></div><div><label>Username</label><input name="username" required></div><div><label>Email</label><input name="email" required></div><div><label>Phone</label><input name="phone" inputmode="numeric" required></div><div><label>Type</label><select name="type"><option>Student</option><option>Faculty</option></select></div><div><label>Password</label><input name="password" type="password" required></div></div><div id="mfb" class="feedback"></div><div class="actions mt"><button class="btn">Create Member</button></div></form>`}
if(type==="issue"){title="Issue Book";body=`<form id="modalForm"><label>Book</label><select name="book" required>${db.books.filter(b=>b.available>0).map(b=>`<option value="${b.id}">${esc(b.title)} (${b.available} available)</option>`).join("")}</select><label>Member</label><select name="member" required>${db.users.filter(u=>u.role==="member").map(u=>`<option value="${u.id}">${esc(u.name)}</option>`).join("")}</select><label>Due date</label><input name="due" type="date" required value="${new Date(Date.now()+db.settings.loanDays*86400000).toISOString().slice(0,10)}"><div id="mfb" class="feedback"></div><div class="actions mt"><button class="btn">Issue</button></div></form>`}
document.body.insertAdjacentHTML("beforeend",`<div class="modal"><div class="modal-box"><div class="modal-head"><h2>${title}</h2><button class="close" id="close">×</button></div>${body}</div></div>`);$(".modal").onclick=e=>{if(e.target.classList.contains("modal"))e.target.remove()};$("#close").onclick=()=>$(".modal").remove();$("#modalForm").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),fb=$("#mfb");if(type==="book"){let b={id:uid(),title:f.get("title").trim(),author:f.get("author").trim(),isbn:f.get("isbn").replace(/[- ]/g,""),publisher:f.get("publisher").trim(),year:Number(f.get("year")||0),genre:f.get("genre").trim(),tags:f.get("tags").trim(),copies:Number(f.get("copies")),available:Number(f.get("copies")),price:Number(f.get("price")||0),rating:Number(f.get("rating")||0),cover:f.get("cover").trim()};if(!b.title||!nameOK(b.author)||!isbnOK(b.isbn)||!b.genre)return fb.textContent="Check title, author, ISBN and genre.";if(db.books.some(x=>x.isbn===b.isbn))return fb.textContent="ISBN already exists.";if(b.year&&(b.year<1000||b.year>new Date().getFullYear()+1))return fb.textContent="Invalid publication year.";if(b.rating<0||b.rating>5)return fb.textContent="Rating must be 0 to 5.";if(b.cover&&!/^https?:\\/\\//i.test(b.cover))return fb.textContent="Cover URL must use HTTP or HTTPS.";db.books.push(b);audit("Added book",b.title)}
if(type==="member"){let n=f.get("name").trim(),un=f.get("username"),em=f.get("email").toLowerCase(),ph=f.get("phone"),pw=f.get("password");if(!nameOK(n))return fb.textContent="Name may contain only alphabets and spaces.";if(!userOK(un))return fb.textContent="Username may contain only alphabets and underscores.";if(db.users.some(x=>x.username===un))return fb.textContent="Username already exists.";if(!emailOK(em,db.settings.allowedDomains||[]))return fb.textContent="Email domain is not allowed.";if(!phoneOK(ph))return fb.textContent="Phone number must contain digits only.";if(pw.length<8)return fb.textContent="Password must contain at least 8 characters.";db.users.push({id:uid(),name:n,username:un,email:em,phone:ph,memberType:f.get("type"),password:pw,role:"member",createdAt:Date.now()});audit("Added member",n)}
if(type==="issue"){let b=db.books.find(x=>x.id===f.get("book")),mid=f.get("member");if(!b||b.available<1)return fb.textContent="No copy available.";if(db.loans.filter(l=>l.memberId===mid&&!l.returned).length>=db.settings.maxLoans)return fb.textContent="Member has reached the loan limit.";db.loans.push({id:uid(),bookId:b.id,memberId:mid,issueDate:new Date().toISOString().slice(0,10),dueDate:f.get("due"),returned:false,renewals:0});b.available--;audit("Issued book",b.title);notify(mid,"Book issued",`${b.title} is due on ${f.get("due")}.`)}
save();$(".modal").remove();render()}}
function audit(action,details){let u=currentUser();db.audit.push({id:uid(),time:Date.now(),user:u?.username||"system",action,details})}
function notify(uid,title,text){db.notifications.push({id:uid(),memberId:uid,title,text,time:Date.now()})}
function bindGlobal(){document.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>modal(b.dataset.action));$("#search")?.addEventListener("input",e=>{search=e.target.value;let pos=e.target.selectionStart;render();$("#search")?.focus();$("#search").selectionStart=$("#search").selectionEnd=pos});document.querySelectorAll("[data-delete-book]").forEach(b=>b.onclick=()=>{let id=b.dataset.deleteBook;if(db.loans.some(l=>l.bookId===id&&!l.returned))return alert("Cannot delete a book with an active loan.");if(confirm("Delete this book?")){db.books=db.books.filter(x=>x.id!==id);save();render()}});document.querySelectorAll("[data-delete-user]").forEach(b=>b.onclick=()=>{let id=b.dataset.deleteUser;if(db.loans.some(l=>l.memberId===id&&!l.returned))return alert("Member has an active loan.");if(confirm("Delete this member?")){db.users=db.users.filter(x=>x.id!==id);save();render()}});document.querySelectorAll("[data-return]").forEach(b=>b.onclick=()=>{let l=db.loans.find(x=>x.id===b.dataset.return);if(l&&!l.returned){l.returned=true;let bk=db.books.find(x=>x.id===l.bookId);if(bk)bk.available++;let due=new Date(l.dueDate),now=new Date();let days=Math.max(0,Math.ceil((now-due)/86400000));if(days)db.fines.push({id:uid(),memberId:l.memberId,bookId:l.bookId,amount:days*db.settings.dailyFine,paid:false});save();render()}});document.querySelectorAll("[data-pay]").forEach(b=>b.onclick=()=>{let f=db.fines.find(x=>x.id===b.dataset.pay);if(f){f.paid=true;save();render()}});document.querySelectorAll("[data-theme]").forEach(b=>b.onclick=()=>{localStorage.setItem(T,b.dataset.theme);applyTheme();render()});$("#settings")?.addEventListener("submit",e=>{e.preventDefault();let f=new FormData(e.target),domains=f.get("domains").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean);if(domains.some(x=>!/^[a-z0-9-]+(?:\\.[a-z0-9-]+){1,2}$/.test(x)))return alert("Invalid domain.");db.settings.libraryName=f.get("libraryName").trim();db.settings.allowedDomains=[...new Set(domains)];db.settings.loanDays=+f.get("loanDays");db.settings.maxLoans=+f.get("maxLoans");db.settings.maxRenewals=+f.get("maxRenewals");db.settings.dailyFine=+f.get("dailyFine");db.settings.reservationLimit=+f.get("reservationLimit");save();render()});$("#clearData")?.addEventListener("click",()=>{if(confirm("Clear all library data and return to first-time setup?")){localStorage.removeItem(K);sessionStorage.removeItem(S);location.reload()}});$("#restore")?.addEventListener("change",async e=>{let file=e.target.files[0];if(!file)return;try{let x=JSON.parse(await file.text());if(!x.users||!x.settings)throw 0;db=x;save();alert("Backup restored.");render()}catch{alert("Invalid backup file.")}});document.querySelectorAll("[data-export]").forEach(b=>b.onclick=()=>exportData(b.dataset.export))}
function csv(rows){return rows.map(r=>r.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(",")).join("\\n")}
function download(name,data,type){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportData(t){if(t==="backup")return download("library-management-backup.json",JSON.stringify(db,null,2),"application/json");let rows=[];if(t==="books"){rows=[["Title","Author","ISBN","Publisher","Year","Genre","Copies","Available","Price","Rating"],...db.books.map(b=>[b.title,b.author,b.isbn,b.publisher,b.year,b.genre,b.copies,b.available,b.price,b.rating])]}if(t==="members")rows=[["Name","Username","Email","Phone","Type"],...db.users.filter(u=>u.role==="member").map(u=>[u.name,u.username,u.email,u.phone,u.memberType])];if(t==="loans")rows=[["Book","Member","Issue","Due","Returned"],...db.loans.map(l=>[db.books.find(b=>b.id===l.bookId)?.title,db.users.find(u=>u.id===l.memberId)?.name,l.issueDate,l.dueDate,l.returned])];download(`library-${t}.csv`,csv(rows),"text/csv")}
function render(){db=read();let u=currentUser();if(!db.users.length)return setup();if(!u)return login();if(u.role==="member")return shell(member());let b=page==="dashboard"?dashboard():page==="books"?books():page==="members"?members():page==="circulation"?circulation():page==="reservations"?reservations():page==="fines"?fines():page==="reports"?reports():page==="notifications"?notifications():page==="audit"?audit():settings();shell(b);bindGlobal()}
window.addEventListener("pageshow",()=>{applyTheme();render()});render();
})();